version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis_server
  redis_server:
    image: redis
    ports:
      - "6379:6379"
  migration:
    image: migration
    build:
      context: .
      dockerfile: Dockerfile.migration
    volumes:
      - C:\Users\Денис\PycharmProjects\DKR(main)\dkr_site\db.sqlite3